codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 0.8
        threshold: 0.02
    patch:
      default:
        target: 0.8
        threshold: 0.05

ignore:
  - "src/test/**"
